---
sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:  

         
# https://docs.rundeck.com/docs/administration/install/docker.html#rundeck-enterprise
    - name: "deploy Rundeck with Docker"
      dist: bionic
      language: python
      python: 3.7
      services: docker
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
          # https://docs.rundeck.com/downloads.html
          - docker pull rundeck/rundeck:3.3.5
          - docker image ls 
          - docker run --name some-rundeck -p 4440:4440 -v data:/home/rundeck/server/data rundeck/rundeck:3.3.5 &
          - docker image ls 
          - docker image ps
          # Grails application running at http://0.0.0.0:4440/ in environment: production
          - sudo cat /etc/hosts
          - curl -I 127.0.0.1
          - curl  -v http://localhost:4440
      after_success:
        - deactivate
        - sudo vagrant destroy -f # required to run Vagrantfile template        
        - sudo rm Vagrantfile # required to run Vagrantfile template 
